language: csharp
solution: FileDictionary.sln

script:
    - nuget restore
    - msbuild /p:Configuration=Debug FileDictionary.sln
    - cd work
    - mkdir dic
    - mono ../packages/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ../bin/Debug/FileDictionaryTest.dll
